### ISSUE TITLE
Retirar - [Insight] Text files should end with a newline character - in laravel/phpspec.yml, line 5

### ISSUE THREAD

**Issue by ravelmello** [ravelmello/treinamentolaravel#3]
**[in laravel/phpspec.yml, line 5](https://github.com/ravelmello/treinamentolaravel/blob/a8480fe8881bb6829488e405118f72dcd0370f5b/laravel/phpspec.yml#L5)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
suites:
    main:
        namespace: App
        psr4_prefix: App
        src_path: app
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/d150d79d-0a05-44a8-a02c-4681b1d574ef/analyses/1?status=violations)_
